fix: DeprecationWarning on withitem ast generated
/Users/noor/src/shell/oxsh/tests/conftest.py:37: DeprecationWarning:
withitem.__init__ got an unexpected keyword argument 'end_col_offset'.
Support for arbitrary keyword arguments is deprecated and will be
removed in Python 3.15.
    return Parser.parse_file(path)